"""
Event-driven signed-particle simulation for V(x) = omega^2 x^2/2 + V1 sin(k x)
(hbar = m = 1), used by src/demo_event_driven_branching.py.

The quadratic part is applied as an exact classical flow (rigid rotation in
phase space); the sine is applied as momentum-jump events on a Poisson clock.
Events are generated by *thinning* (Lewis & Shedler 1979): candidate times at
the global bound lam_max = V1/hbar, accepted with probability
|Gamma(x(t))| / lam_max where Gamma(x) = (V1/hbar) cos(k x) is Takabayasi's
single-mode amplitude (Lemma T1).  Thinning is exact for a rate that varies
along the flight; no time step enters the dynamics.

Three clocks are provided for the pair rule:

  thin      Poisson, by thinning (exact; above).
  frozen    Poisson with the rate frozen at the start of each flight (biased;
            the supplement's section 7).
  fire      deterministic integrate-and-fire (step 23, Proposition Q11):
            every particle carries an integrator C advanced along its own
            flight by dC/dt = Gamma(x(t)), signed, and fires each time C
            crosses an integer, with orientation sgn(dC) = sgn Gamma.  Only
            the initial phases C(0) are random (uniform on [0, 1); children
            get fresh ones), so a given initial ensemble evolves
            deterministically.  The integral is Simpson's rule on sub-steps
            of dt_fire, and crossing times are interpolated linearly in C.
  fire-abs  the same with dC/dt = |Gamma| (a gross clock, no cancelling
            back-and-forth crossings where Gamma changes sign).

Two event rules are provided:

  pair   signed pair branching (the QLE generator):  the parent persists and
         two children are born at the same x, at p - a with sign s*sgn(Gamma)
         and at p + a with sign -s*sgn(Gamma), a = hbar k/2.
  one    one-particle positive Poisson kicks (Cyganski's slide):  the particle
         jumps by  step * sgn(F(x)),  F = -V1 k cos(k x), at rate
         |F| / step.  No signs, no births.

Annihilation of opposite-signed particles is done on a phase-space cell
lattice at synchronisation times.  annihilation="keep": survivors keep their
own positions.  annihilation="centroid": survivors are then shifted rigidly so
that each cell's signed zeroth AND first moments in x and p are unchanged.
"""

from __future__ import annotations

import numpy as np


class EventBranching:
    def __init__(self, omega, V1, k, rule="pair", step=None, clock="thin",
                 cell=(0.25, 0.5), annihilation="keep", rng=None, dt_fire=0.005):
        self.om, self.V1, self.k = float(omega), float(V1), float(k)
        self.rule = rule
        self.a = 0.5 * self.k                    # hbar k / 2
        self.step = self.k if step is None else float(step)   # one-particle kick
        self.clock = clock                       # "thin" (exact) or "frozen"
        self.cell = cell
        self.annihilation = annihilation         # "keep" or "centroid"
        self.rng = np.random.default_rng() if rng is None else rng
        self.lam_max = self.V1 if rule == "pair" else self.V1 * self.k / self.step
        self.n_candidates = 0
        self.n_events = 0
        self.dt_fire = float(dt_fire)
        self.C = None              # integrator phases, aligned with the particles (fire clocks)
        if clock.startswith("fire") and rule != "pair":
            raise ValueError("the fire clocks are implemented for the pair rule")

    # --------------------------------------------------------------
    def rate(self, x):
        """Event rate per particle at x."""
        g = self.V1 * np.abs(np.cos(self.k * x))
        return g if self.rule == "pair" else g * self.k / self.step

    def flow(self, x, p, dt):
        """Exact harmonic flow (m = 1) over per-particle intervals dt."""
        c, s = np.cos(self.om * dt), np.sin(self.om * dt)
        return x * c + p * s / self.om, -x * self.om * s + p * c

    # --------------------------------------------------------------
    def advance(self, x, p, sg, t0, t1):
        """Advance all particles from t0 to t1 with event-driven jumps."""
        if self.clock.startswith("fire"):
            return self._advance_fire(x, p, sg, t0, t1)
        tcur = np.full(x.shape, t0)
        done_x, done_p, done_s = [], [], []
        while x.size:
            if self.clock == "thin":
                tau = self.rng.exponential(1.0 / self.lam_max, x.size)
            else:  # frozen: rate evaluated at the start of the flight
                r = np.maximum(self.rate(x), 1e-300)
                tau = self.rng.exponential(1.0, x.size) / r
            tn = tcur + tau
            fin = tn >= t1
            if fin.any():
                xf, pf = self.flow(x[fin], p[fin], t1 - tcur[fin])
                done_x.append(xf); done_p.append(pf); done_s.append(sg[fin])
            keep = ~fin
            x, p, sg, tcur, tn = x[keep], p[keep], sg[keep], tcur[keep], tn[keep]
            if not x.size:
                break
            x, p = self.flow(x, p, tn - tcur)
            tcur = tn
            self.n_candidates += x.size
            if self.clock == "thin":
                acc = self.rng.random(x.size) * self.lam_max < self.rate(x)
            else:
                acc = np.ones(x.size, bool)
            if not acc.any():
                continue
            self.n_events += int(acc.sum())
            cosk = np.cos(self.k * x[acc])
            if self.rule == "pair":
                sgam = np.sign(cosk)
                xa, pa, sa, ta = x[acc], p[acc], sg[acc], tcur[acc]
                # children: sign s*sgn(Gamma) at p - a, sign -s*sgn(Gamma) at p + a
                x = np.concatenate([x, xa, xa])
                p = np.concatenate([p, pa - self.a, pa + self.a])
                sg = np.concatenate([sg, sa * sgam, -sa * sgam]).astype(np.int8)
                tcur = np.concatenate([tcur, ta, ta])
            else:
                F = -self.V1 * self.k * cosk
                p = p.copy()
                p[acc] += self.step * np.sign(F)
        if done_x:
            return np.concatenate(done_x), np.concatenate(done_p), np.concatenate(done_s)
        return x, p, sg

    def _advance_fire(self, x, p, sg, t0, t1):
        """Integrate-and-fire clocks (Proposition Q11 of step 23)."""
        x, p, sg = x.copy(), p.copy(), sg.copy()
        if self.C is None or self.C.size != x.size:
            self.C = self.rng.random(x.size)
        C = self.C
        signed = self.clock == "fire"
        gam = lambda xx: self.V1 * np.cos(self.k * xx)
        nsub = max(1, int(np.ceil((t1 - t0) / self.dt_fire - 1e-9)))
        edges = np.linspace(t0, t1, nsub + 1)
        for Ta, Tb in zip(edges[:-1], edges[1:]):
            tcur = np.full(x.size, Ta)
            act = np.ones(x.size, bool)
            while act.any():
                i = np.flatnonzero(act)
                dt = Tb - tcur[i]
                xm, _ = self.flow(x[i], p[i], 0.5 * dt)
                x1, p1 = self.flow(x[i], p[i], dt)
                g = [gam(x[i]), gam(xm), gam(x1)]
                if not signed:
                    g = [np.abs(v) for v in g]
                dC = dt * (g[0] + 4 * g[1] + g[2]) / 6
                Cn = C[i] + dC
                fl = np.floor(C[i])
                cr = np.floor(Cn) != fl
                ok = ~cr                                   # reach Tb without firing
                j = i[ok]
                x[j], p[j], C[j], tcur[j] = x1[ok], p1[ok], Cn[ok], Tb
                act[j] = False
                if not cr.any():
                    break
                j = i[cr]
                up = dC[cr] > 0
                n = np.where(up, fl[cr] + 1, fl[cr])        # the integer crossed
                frac = np.clip((n - C[j]) / dC[cr], 0.0, 1.0)
                x[j], p[j] = self.flow(x[j], p[j], frac * dt[cr])
                tcur[j] += frac * dt[cr]
                C[j] = n + np.where(up, 1e-12, -1e-12)
                if signed:
                    sgam = np.where(up, 1, -1)
                else:
                    sgam = np.sign(gam(x[j])).astype(int)
                self.n_events += j.size
                xa, pa, sa = x[j], p[j], sg[j]
                x = np.concatenate([x, xa, xa])
                p = np.concatenate([p, pa - self.a, pa + self.a])
                sg = np.concatenate([sg, sa * sgam, -sa * sgam]).astype(np.int8)
                tcur = np.concatenate([tcur, tcur[j], tcur[j]])
                C = np.concatenate([C, self.rng.random(2 * j.size)])
                act = np.concatenate([act, np.ones(2 * j.size, bool)])
        self.C = C
        return x, p, sg

    # --------------------------------------------------------------
    def annihilate(self, x, p, sg):
        """Cancel opposite signs cell by cell; survivors keep their positions."""
        if self.rule != "pair" or x.size == 0:
            return x, p, sg
        hx, hp = self.cell
        ix = np.floor(x / hx).astype(np.int64)
        ip = np.floor(p / hp).astype(np.int64)
        cid = (ix + (1 << 20)) * (1 << 21) + (ip + (1 << 20))
        key = self.rng.random(x.size)
        order = np.lexsort((key, sg, cid))
        cid_s, sg_s = cid[order], sg[order]
        # group (cell, sign)
        grp = np.concatenate([[True], (cid_s[1:] != cid_s[:-1]) | (sg_s[1:] != sg_s[:-1])])
        gstart = np.flatnonzero(grp)
        gsize = np.diff(np.append(gstart, cid_s.size))
        gid = np.cumsum(grp) - 1
        rank = np.arange(cid_s.size) - gstart[gid]
        # count of opposite sign in the same cell
        ucell, cinv = np.unique(cid_s, return_inverse=True)
        npos = np.bincount(cinv, weights=(sg_s > 0), minlength=ucell.size)
        nneg = np.bincount(cinv, weights=(sg_s < 0), minlength=ucell.size)
        opp = np.where(sg_s > 0, nneg[cinv], npos[cinv])
        survive = rank < (gsize[gid] - opp)
        idx = order[survive]
        xo, po, so = x[idx], p[idx], sg[idx]
        if self.C is not None and self.C.size == x.size:
            self.C = self.C[idx]
        if self.annihilation == "centroid":
            # shift survivors so each cell's signed first moments are preserved
            xs_, ps_ = x[order], p[order]
            sx_b = np.bincount(cinv, weights=sg_s * xs_, minlength=ucell.size)
            sp_b = np.bincount(cinv, weights=sg_s * ps_, minlength=ucell.size)
            ci = cinv[survive]
            sx_a = np.bincount(ci, weights=so * xo, minlength=ucell.size)
            sp_a = np.bincount(ci, weights=so * po, minlength=ucell.size)
            net = npos - nneg
            with np.errstate(divide="ignore", invalid="ignore"):
                dx = np.where(net != 0, (sx_b - sx_a) / net, 0.0)
                dp = np.where(net != 0, (sp_b - sp_a) / net, 0.0)
            xo, po = xo + dx[ci], po + dp[ci]
        return xo, po, so

    # --------------------------------------------------------------
    def run(self, x, p, sg, times, t_sync, callback=None):
        """Evolve to each time in `times`, annihilating every t_sync.
        Returns dict t -> (x, p, sg) and a population log
        (t, total, positons, negatons).  callback(t, x, p, sg) is called at
        every synchronisation time, after annihilation."""
        out, log = {}, []
        t = 0.0
        grid = np.unique(np.concatenate([np.arange(0.0, max(times) + 1e-12, t_sync),
                                         np.asarray(times, float)]))
        for tn in grid[1:]:
            x, p, sg = self.advance(x, p, sg, t, tn)
            x, p, sg = self.annihilate(x, p, sg)
            t = tn
            log.append((t, x.size, int((sg > 0).sum()), int((sg < 0).sum())))
            if callback is not None:
                callback(t, x, p, sg)
            for tt in times:
                if abs(tt - t) < 1e-12:
                    out[tt] = (x.copy(), p.copy(), sg.copy())
        return out, np.array(log)
