#!/usr/bin/env python3
r"""
Independent re-implementation of Cyganski's event-driven "virtual-photon pair
branching" (call of 2026-09-29), for the supplement
docs/supplement/poisson_kicks_and_pair_branching.md, Parts F-M (prefix X).

Model.  V(x) = omega^2 x^2 / 2 + V1 sin(k x),  hbar = m = 1,
omega = 0.4, V1 = 0.5, k = 1, initial Gaussian at rest at x0 = 6, sigma_x = 0.7.
The quadratic part is an exact classical flow; the sine acts through events on
a Poisson clock generated by thinning (src/wpmwlib/event_branching.py).

Parts
  F  Two independent references: split-operator Schroedinger (|psi|^2) and a
     spectral QLE solver on (x, p).  They must agree.
  G  Infinite-N limits.  Signed pair branching IS the QLE (Lemma T1);
     one-particle positive kicks (step hbar k, Cyganski's slide, and hbar k/2)
     are not: marginals, phase space, and the exact heating law
     d<H>/dt = <M2>/2 (Proposition X4).
  H  Pair branching WITHOUT annihilation is unbiased:  error * sqrt(N0) const.
  I  With cell annihilation: N0-scaling at three momentum cells h_p.  The error
     plateaus -- a bias set by h_p, not by N0 (Proposition X5).
  J  What controls the bias: h_p versus h_x, and the synchronisation interval.
  K  Negative control by Monte Carlo: one-particle kicks agree with their own
     master equation and not with the QLE; measured heating vs Proposition X4.
  L  Clock: thinning (exact) versus a rate frozen at the start of each flight.
"""

import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wpmwlib.wpmw_utils import output_path, docs_path  # noqa: E402
from wpmwlib.event_branching import EventBranching  # noqa: E402

OM, V1, K = 0.4, 0.5, 1.0
X0, SX = 6.0, 0.7
SP = 1.0 / (2 * SX)
T_OBS = 9.0
FIG1, FIG2 = "event_branching_phase_space.png", "event_branching_bias.png"
QUICK = os.environ.get("WPMW_QUICK", "") == "1"   # smaller N0 for a smoke test


def banner(s):
    print("\n" + "=" * 72)
    print(s)
    print("=" * 72, flush=True)


def V(x):
    return 0.5 * OM ** 2 * x ** 2 + V1 * np.sin(K * x)


# ----------------------------------------------------------------------
# spectral phase-space solver (QLE, or quadratic force + positive kicks)
# ----------------------------------------------------------------------
MX, NP, LX, LP = 256, 512, 25.6, 32.0
xg = (np.arange(MX) - MX // 2) * (LX / MX)
pg = (np.arange(NP) - NP // 2) * (LP / NP)
DXG, DPG = LX / MX, LP / NP
X, P = np.meshgrid(xg, pg, indexing="xy")
kx = 2 * np.pi * np.fft.fftfreq(MX, d=DXG)
kp = 2 * np.pi * np.fft.fftfreq(NP, d=DPG)


def W_init(Xa, Pa):
    return np.exp(-(Xa - X0) ** 2 / (2 * SX ** 2) - Pa ** 2 / (2 * SP ** 2)) / (2 * np.pi * SX * SP)


def spectral(times, rule="qle", step=K, dt=0.01):
    """Strang split.  rule='qle': exact potential symbol i[V(x+k/2)-V(x-k/2)];
    rule='one': omega^2 x force + rate |F|/step jumps of step*sgn F."""
    W = W_init(X, P).astype(complex)
    KP, XX = kp[:, None], xg[None, :]
    if rule == "qle":
        G = 1j * (V(XX + KP / 2) - V(XX - KP / 2))
    else:
        F = -V1 * K * np.cos(K * XX)
        G = 1j * OM ** 2 * XX * KP + (np.abs(F) / step) * (np.exp(-1j * KP * step * np.sign(F)) - 1)
    kick = np.exp(G * dt)
    half = np.exp(-1j * kx[None, :] * P * dt / 2)
    out = {}
    nmax = int(round(max(times) / dt))
    want = {int(round(t / dt)): t for t in times}
    for i in range(1, nmax + 1):
        W = np.fft.ifft(np.fft.fft(W, axis=1) * half, axis=1)
        W = np.fft.ifft(np.fft.fft(W, axis=0) * kick, axis=0)
        W = np.fft.ifft(np.fft.fft(W, axis=1) * half, axis=1)
        if i in want:
            out[want[i]] = W.real.copy()
    return out


def energy(W):
    return float(np.sum((P ** 2 / 2 + V(X)) * W) * DXG * DPG)


def xmean(W):
    return float(np.sum(X * W) * DXG * DPG)


# ----------------------------------------------------------------------
banner("PART F  --  references: Schroedinger |psi|^2 vs spectral QLE")
NS, LS = 4096, 60.0
xs = (np.arange(NS) - NS // 2) * (LS / NS)
dxs = LS / NS
ks = 2 * np.pi * np.fft.fftfreq(NS, d=dxs)
psi = ((2 * np.pi * SX ** 2) ** -0.25 * np.exp(-(xs - X0) ** 2 / (4 * SX ** 2))).astype(complex)
dts = 0.0025
hv, kin = np.exp(-0.5j * V(xs) * dts), np.exp(-0.5j * ks ** 2 * dts)
rho_s = {}
for i in range(1, int(round(T_OBS / dts)) + 1):
    psi = hv * np.fft.ifft(kin * np.fft.fft(hv * psi))
    for t in (4.5, T_OBS):
        if i == int(round(t / dts)):
            rho_s[t] = np.abs(psi) ** 2

t_grid = np.round(np.arange(0.5, 18.0 + 1e-9, 0.5), 3)
t0 = time.time()
Q = spectral(sorted(set(t_grid) | {4.5, T_OBS}))
print(f"  spectral QLE {MX}x{NP}, dt = 0.01: {time.time() - t0:.1f} s")
for t in (4.5, T_OBS):
    rq = Q[t].sum(0) * DPG
    d = np.abs(rq - np.interp(xg, xs, rho_s[t])).max()
    print(f"  t = {t:4.1f}:  max |rho_QLE - |psi|^2| = {d:.2e}   (peak {rho_s[t].max():.4f})")
# return turning point: first maximum of <x> after the left excursion
xm = np.array([xmean(Q[t]) for t in t_grid])
sel = (t_grid > 10)
T_RET = float(t_grid[sel][np.argmax(xm[sel])])
Q.update(spectral([T_RET]))
print(f"  return turning point (max <x> on a 0.5 grid, t > 10): T_ret = {T_RET}"
      f"   <x> = {xmean(Q[T_RET]):.3f}")
E0 = energy(W_init(X, P))
dE_qle = max(abs(energy(Q[t]) - E0) for t in t_grid)
print(f"  QLE energy <H> = {E0:.6f},  max drift over t <= 18: {dE_qle:.2e}")

# ----------------------------------------------------------------------
banner("PART G  --  infinite-N limits: pair branching (= QLE) vs one-particle kicks")
print("  Pair branching:  Gamma(x)[W(p+a)-W(p-a)], a = hbar k/2, IS the sine's exact")
print("  Wigner term (Lemma T1).  Its infinite-N limit is the QLE identically.")
for t in (T_OBS, T_RET):
    print(f"  QLE, t = {t:5.2f}:  negative mass = {-Q[t][Q[t] < 0].sum() * DXG * DPG:.4f}   "
          f"purity 2*pi*hbar*int W^2 = {2 * np.pi * np.sum(Q[t] ** 2) * DXG * DPG:.4f}")
ONE = {}
for label, step in (("step hbar k  ", K), ("step hbar k/2", K / 2)):
    t_fine = np.round(np.arange(0.1, 18.0 + 1e-9, 0.1), 3)
    R1 = spectral(sorted(set([4.5, T_OBS, T_RET]) | set(t_fine)), rule="one", step=step)
    ONE[step] = R1
    for t in (T_OBS, T_RET):
        l1W = np.abs(R1[t] - Q[t]).sum() * DXG * DPG
        l1r = np.abs(R1[t].sum(0) - Q[t].sum(0)).sum() * DPG * DXG
        neg = -R1[t][R1[t] < 0].sum() * DXG * DPG
        pur = 2 * np.pi * np.sum(R1[t] ** 2) * DXG * DPG
        print(f"  one-particle, {label}, t = {t:5.2f}:  ||W - W_QLE||_1 = {l1W:.3f}   "
              f"||rho - rho_QLE||_1 = {l1r:.3f}   negative mass = {neg:.2e}   "
              f"purity 2*pi*hbar*int W^2 = {pur:.4f}")
    # Proposition X4: d<H>/dt = <M2>/2,  M2 = step |F| = step V1 k |cos kx|
    tt_ = np.concatenate([[0.0], t_fine])
    Et = np.array([E0] + [energy(R1[t]) for t in t_fine])
    W0_ = W_init(X, P)
    rate = np.array([0.5 * step * V1 * K * np.sum(np.abs(np.cos(K * X)) * Wt) * DXG * DPG
                     for Wt in [W0_] + [R1[t] for t in t_fine]])
    pred = E0 + np.concatenate([[0], np.cumsum(0.5 * (rate[1:] + rate[:-1]) * np.diff(tt_))])
    print(f"      heating: <H>(18) - <H>(0) = {Et[-1] - E0:.4f};  "
          f"integral of <M2>/2 = {pred[-1] - E0:.4f};  "
          f"max |<H> - prediction| = {np.abs(Et - pred).max():.2e}")
QLE_W = Q

# ----------------------------------------------------------------------
edges = np.arange(-12.0, 12.0 + 1e-9, 0.1)
HX = 0.1
xc = 0.5 * (edges[1:] + edges[:-1])


def ref_bins(rho):
    cum = np.concatenate([[0.0], np.cumsum(rho) * dxs])
    xe = np.concatenate([xs - dxs / 2, [xs[-1] + dxs / 2]])
    return np.diff(np.interp(edges, xe, cum)) / HX


REF = {t: ref_bins(rho_s[t]) for t in rho_s}


def mc(N0, T, seed, rule="pair", cell=(0.1, 0.25), t_sync=0.1, annihilate=True,
       clock="thin", step=K, callback=None, ann_mode="keep"):
    rng = np.random.default_rng(seed)
    x = rng.normal(X0, SX, N0)
    p = rng.normal(0.0, SP, N0)
    s = np.ones(N0, np.int8)
    eb = EventBranching(OM, V1, K, rule=rule, step=step, clock=clock, cell=cell,
                        annihilation=ann_mode, rng=rng)
    if annihilate or rule == "one":
        out, log = eb.run(x, p, s, [T], t_sync, callback=callback)
        x, p, s = out[T]
    else:
        x, p, s = eb.advance(x, p, s, 0.0, T)
        log = np.array([[T, x.size, (s > 0).sum(), (s < 0).sum()]])
    h, _ = np.histogram(x, bins=edges, weights=s.astype(float))
    return h / N0 / HX, (x, p, s), log, eb


def l2(r, T):
    return float(np.sqrt(np.sum((r - REF[T]) ** 2) * HX))


PEAK = int(np.argmax(REF[T_OBS]))
print(f"\n  observation bins: h_x = {HX};  rho_ref peak at x = {xc[PEAK]:.2f}, value {REF[T_OBS][PEAK]:.4f}")

# ----------------------------------------------------------------------
banner("PART H  --  pair branching without annihilation (t = 4.5): unbiased")
H_N = [6250, 25000, 100000] if not QUICK else [6250, 25000]
H_rows = []
for N0 in H_N:
    errs, pops = [], []
    for rep in range(4):
        r, (xx, _, _), _, eb = mc(N0, 4.5, 100 + rep, annihilate=False)
        errs.append(l2(r, 4.5)); pops.append(xx.size / N0)
    e = float(np.sqrt(np.mean(np.square(errs))))
    H_rows.append((N0, e))
    print(f"  N0 = {N0:7d}:  rms L2 error (4 seeds) = {e:.4f}   e*sqrt(N0) = {e*np.sqrt(N0):6.2f}"
          f"   population / N0 = {np.mean(pops):.1f}")

# ----------------------------------------------------------------------
banner("PART I  --  with annihilation on (h_x, h_p) cells, t = 9: N0 scaling")
HP = [0.5, 0.25, 0.125]
NLIST = [(25000, 8), (100000, 4), (400000, 2), (1600000, 1)] if not QUICK else [(25000, 2), (100000, 1)]
I_rows = {}
POOL = {}
BEST = None
for hp in HP:
    rows, pool, wsum = [], np.zeros_like(xc), 0
    for N0, R in NLIST:
        t0 = time.time()
        es, pk = [], []
        for rep in range(R):
            r, state, log, eb = mc(N0, T_OBS, 1000 * rep + N0 % 997, cell=(0.1, hp))
            es.append(l2(r, T_OBS))
            pk.append(r[PEAK - 2:PEAK + 3].mean() / REF[T_OBS][PEAK - 2:PEAK + 3].mean())
            pool += r * N0; wsum += N0
            if hp == HP[-1] and N0 == NLIST[-1][0]:
                BEST = (r, state, log)
            if hp == HP[0] and N0 == NLIST[-1][0]:
                COARSE = r
        e = float(np.sqrt(np.mean(np.square(es))))
        rows.append((N0, e))
        print(f"  h_p = {hp:5.3f}  N0 = {N0:8d} x {R}:  rms L2 = {e:.4f}   e*sqrt(N0) = "
              f"{e*np.sqrt(N0):7.2f}   peak ratio = {np.mean(pk):.3f}   "
              f"max pop/N0 = {log[:, 1].max()/N0:.2f}   ({time.time()-t0:.0f} s)", flush=True)
    I_rows[hp] = np.array(rows)
    pooled = pool / wsum
    POOL[hp] = pooled
    # fit e^2 = b^2 + c/N0
    Ns, Es = I_rows[hp][:, 0], I_rows[hp][:, 1]
    A = np.vstack([np.ones_like(Ns), 1 / Ns]).T
    (b2, cc), *_ = np.linalg.lstsq(A, Es ** 2, rcond=None)
    print(f"      fit e^2 = b^2 + c/N0:  b = {np.sqrt(max(b2, 0)):.4f}   sqrt(c) = {np.sqrt(max(cc, 0)):.1f}"
          f"   ||pooled mean - ref||_2 = {l2(pooled, T_OBS):.4f} (pooled N = {wsum})")
BIAS = {hp: l2(POOL[hp], T_OBS) for hp in HP}
sl = np.polyfit(np.log(HP), np.log([BIAS[h] for h in HP]), 1)[0]
print(f"  bias exponent d log(b)/d log(h_p) = {sl:.2f}")

# ----------------------------------------------------------------------
banner("PART J  --  what sets the bias: h_p, not h_x, not the sync interval")
NJ = 400000 if not QUICK else 50000
J_rows = []
for cell in [(0.05, 0.5), (0.2, 0.5), (0.2, 0.125), (0.4, 0.125)]:
    r, _, _, _ = mc(NJ, T_OBS, 7, cell=cell)
    J_rows.append((cell, l2(r, T_OBS)))
    print(f"  cell (h_x, h_p) = {cell}:  L2 = {l2(r, T_OBS):.4f}")
for ts in (0.05, 0.4, 3.0):
    r, _, log, _ = mc(NJ, T_OBS, 7, cell=(0.1, 0.25), t_sync=ts)
    J_rows.append((("t_sync", ts), l2(r, T_OBS)))
    print(f"  t_sync = {ts:4.2f} (cell 0.1 x 0.25):  L2 = {l2(r, T_OBS):.4f}   max pop/N0 = "
          f"{log[:, 1].max()/NJ:.2f}")
for cell in [(0.2, 0.5), (0.1, 0.25)]:
    r, _, _, _ = mc(NJ, T_OBS, 7, cell=cell, ann_mode="centroid")
    J_rows.append((("centroid",) + cell, l2(r, T_OBS)))
    print(f"  centroid-preserving annihilation, cell {cell}:  L2 = {l2(r, T_OBS):.4f}")

# ----------------------------------------------------------------------
banner("PART K  --  negative control by Monte Carlo: one-particle kicks (step hbar k)")
NK = 400000 if not QUICK else 50000
Hlog = []


def cb(t, x, p, s):
    Hlog.append((t, np.mean(p ** 2 / 2 + V(x)), 0.5 * K * V1 * K * np.mean(np.abs(np.cos(K * x)))))


r1, (x1, p1, s1), _, eb1 = mc(NK, T_OBS, 5, rule="one", step=K, t_sync=0.1, callback=cb)
rho_one = ONE[K][T_OBS].sum(0) * DPG
one_bins = np.interp(xc, xg, rho_one)
print(f"  MC vs its own master equation:  L2 = {np.sqrt(np.sum((r1-one_bins)**2)*HX):.4f}")
print(f"  MC vs QLE:                      L2 = {l2(r1, T_OBS):.4f}")
Hl = np.array(Hlog)
Hpred = Hl[0, 1] + np.concatenate([[0], np.cumsum(0.5 * (Hl[1:, 2] + Hl[:-1, 2]) * np.diff(Hl[:, 0]))])
E_start = energy(W_init(X, P))
print(f"  <H>: t=0 (exact) {E_start:.4f}   MC t=0.1 {Hl[0,1]:.4f}   MC t=9 {Hl[-1,1]:.4f}   "
      f"prediction from MC's own <M2>/2: {Hpred[-1]:.4f}   QLE: {E0:.4f}")
print(f"  events per initial particle: {eb1.n_events / NK:.2f}   (acceptance "
      f"{eb1.n_events / max(eb1.n_candidates, 1):.3f})")

# ----------------------------------------------------------------------
banner("PART L  --  clock: thinning vs rate frozen at the start of each flight")
print("  no annihilation, t = 4.5, rms over 4 seeds (the sensitive test)")
for clk in ("thin", "frozen"):
    for N0 in ([25000, 100000, 400000] if not QUICK else [25000]):
        es = []
        for rep in range(4):
            r, _, _, eb = mc(N0, 4.5, 50 + rep, annihilate=False, clock=clk)
            es.append(l2(r, 4.5))
        e = float(np.sqrt(np.mean(np.square(es))))
        print(f"  {clk:6s} N0 = {N0:7d}:  rms L2 = {e:.4f}   e*sqrt(N0) = {e*np.sqrt(N0):6.2f}"
              f"   events / N0 = {eb.n_events / N0:.2f}")

# ----------------------------------------------------------------------
import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

rB, (xb, pb, sb), logB = BEST
bx = np.arange(-10, 10 + 1e-9, 0.2)
bp = np.arange(-5, 5 + 1e-9, 0.25)
Hmc, _, _ = np.histogram2d(pb, xb, bins=[bp, bx], weights=sb.astype(float))
Hmc /= (NLIST[-1][0] * 0.2 * 0.25)
# QLE averaged onto the same bins
from scipy.interpolate import RegularGridInterpolator  # noqa: E402
fQ = RegularGridInterpolator((pg, xg), QLE_W[T_OBS], bounds_error=False, fill_value=0)
xf = np.arange(-10 + 0.025, 10, 0.05); pf = np.arange(-5 + 0.03125, 5, 0.0625)
PF, XF = np.meshgrid(pf, xf, indexing="ij")
Qf = fQ((PF, XF)).reshape(len(pf), len(xf))
Qb = Qf.reshape(len(bp) - 1, 4, len(bx) - 1, 4).mean(axis=(1, 3))
vm = 0.33
fig, ax = plt.subplots(2, 3, figsize=(15, 8.6))
ext = [-10, 10, -5, 5]
ax[0, 0].imshow(Qb, origin="lower", extent=ext, cmap="RdBu_r", vmin=-vm, vmax=vm, aspect="auto")
ax[0, 0].set_title(f"(a) QLE Wigner, t = {T_OBS}")
ax[0, 1].imshow(Hmc, origin="lower", extent=ext, cmap="RdBu_r", vmin=-vm, vmax=vm, aspect="auto")
ax[0, 1].set_title(f"(b) event-driven pair branching, N0 = {NLIST[-1][0]:,}, $h_p$ = {HP[-1]}")
im = ax[0, 2].imshow(Hmc - Qb, origin="lower", extent=ext, cmap="RdBu_r", vmin=-0.05, vmax=0.05, aspect="auto")
ax[0, 2].set_title("(c) (b) - (a)")
fig.colorbar(im, ax=ax[0, 2], fraction=0.046)
R1 = ONE[K]
ax[1, 0].imshow(R1[T_RET][(pg >= -5) & (pg < 5)][:, (xg >= -10) & (xg < 10)], origin="lower",
                extent=ext, cmap="RdBu_r", vmin=-0.1, vmax=0.1, aspect="auto")
ax[1, 0].contour(xg, pg, QLE_W[T_RET], levels=[-0.1, 0.1], colors=["b", "r"], linewidths=0.7)
ax[1, 0].set_xlim(-10, 10); ax[1, 0].set_ylim(-5, 5)
ax[1, 0].set_title(f"(d) one-particle kicks, infinite N, t = {T_RET}\n(colour scale $\\pm$0.1; contours: QLE $\\pm$0.1)")
for a_ in (ax[0, 0], ax[0, 1], ax[0, 2], ax[1, 0]):
    a_.set_xlabel("x"); a_.set_ylabel("p")
ax[1, 1].plot(xc, REF[T_OBS], "k", lw=1.6, label="QLE ($|\\psi|^2$)")
ax[1, 1].plot(xc, COARSE, color="C3", lw=1, label=f"pair MC, $h_p$ = {HP[0]}")
ax[1, 1].plot(xc, rB, color="C0", lw=1, label=f"pair MC, $h_p$ = {HP[-1]}")
ax[1, 1].plot(xc, r1, color="C2", lw=1, ls="--", label="one-particle MC")
ax[1, 1].set_xlim(-10, 0); ax[1, 1].set_xlabel("x"); ax[1, 1].set_ylabel(r"$\rho(x)$")
ax[1, 1].set_title(f"(e) position marginal, t = {T_OBS}"); ax[1, 1].legend(fontsize=8)
ax[1, 2].plot(Hl[:, 0], Hl[:, 1], color="C2", label="one-particle MC $\\langle H\\rangle$")
ax[1, 2].plot(Hl[:, 0], Hpred, "k--", lw=1, label=r"$E_0+\frac{1}{2}\int\langle M_2\rangle\,dt$")
ax[1, 2].axhline(E0, color="C0", label="QLE (conserved)")
ax[1, 2].set_xlabel("t"); ax[1, 2].set_title("(f) heating law, Proposition X4"); ax[1, 2].legend(fontsize=8)
fig.tight_layout()
fig.savefig(output_path(FIG1), dpi=130, bbox_inches="tight")
d_ = docs_path(FIG1)
if d_:
    fig.savefig(d_, dpi=130, bbox_inches="tight")

fig, ax = plt.subplots(1, 3, figsize=(15, 4.3))
Hn = np.array(H_rows)
ax[0].loglog(Hn[:, 0], Hn[:, 1], "ks--", label="no annihilation (t = 4.5)")
for hp, c_ in zip(HP, ("C3", "C1", "C0")):
    ax[0].loglog(I_rows[hp][:, 0], I_rows[hp][:, 1], "o-", color=c_, label=f"$h_p$ = {hp}")
    ax[0].axhline(BIAS[hp], color=c_, ls=":", lw=1)
nn = np.array([6e3, 2e6])
ax[0].loglog(nn, Hn[0, 1] * np.sqrt(Hn[0, 0] / nn), "k:", lw=1, label=r"$\propto N_0^{-1/2}$")
ax[0].set_xlabel("$N_0$"); ax[0].set_ylabel(r"$L^2$ error of $\rho(x)$")
ax[0].set_title("(a) error vs $N_0$ (dotted: pooled bias)"); ax[0].legend(fontsize=8)
hps = [c[1] for c, _ in J_rows[:4]]
ax[1].loglog(HP, [BIAS[h] for h in HP], "o-", color="C0", label="bias, $h_x$ = 0.1 (pooled)")
for j, (cell, e) in enumerate(J_rows[:4]):
    ax[1].loglog(cell[1], e, "x", color="C3", ms=8)
    ax[1].annotate(f"$h_x$={cell[0]}", (cell[1], e), fontsize=7,
                   xytext=(-42 if j % 2 == 0 else 6, 6 if j % 2 == 0 else -12), textcoords="offset points")
ax[1].set_xticks(HP); ax[1].set_xticklabels([str(h) for h in HP]); ax[1].minorticks_off()
ax[1].loglog(HP, BIAS[HP[0]] * (np.array(HP) / HP[0]), "k:", lw=1, label=r"$\propto h_p$")
ax[1].set_xlabel("$h_p$"); ax[1].set_title("(b) bias is set by the momentum cell"); ax[1].legend(fontsize=8)
ax[2].plot(logB[:, 0], logB[:, 2] / NLIST[-1][0], label="positons")
ax[2].plot(logB[:, 0], logB[:, 3] / NLIST[-1][0], label="negatons")
ax[2].set_xlabel("t"); ax[2].set_ylabel("count / $N_0$")
ax[2].set_title(f"(c) populations, $h_p$ = {HP[-1]}, $N_0$ = {NLIST[-1][0]:,}"); ax[2].legend(fontsize=8)
fig.tight_layout()
fig.savefig(output_path(FIG2), dpi=130, bbox_inches="tight")
d_ = docs_path(FIG2)
if d_:
    fig.savefig(d_, dpi=130, bbox_inches="tight")
print(f"\nwrote {output_path(FIG1)}\nwrote {output_path(FIG2)}")
