"""
Relational (all-pairs) misalignment, and the carrier-lock condition it needs.

Companion to a proposed revision of
``docs/algorithm/phase_alignment_microdynamics_algorithm.md`` §2.2, which
currently stores on every sea particle a permanent index to a partner and
defines the misalignment as the transported-phase difference of that stored
pair.  The alternative under test (B. Page, July 2026) is to define

    mu_{ij}(x,t) = Phi_i(x,t) - Phi_j(x,t)   (mod 2 pi)

for *every* ordered pair of world-particle indices, storing no partnership
at all.

The result is that the alternative works, but not for free.  It is exactly
equivalent to the indexed form under one extra condition -- that the sea's
*carrier* phase be locked across pairs at a site, not merely matched within
each pair -- and it is inequivalent, in the mean and not just in variance,
when that condition fails.  The condition is not currently stated anywhere
in the model; it is the price of the reformulation, and it is testable.

Parts:

  A  Coboundary structure.  mu_{ij} is antisymmetric and satisfies the
     triangle (cocycle) identity exactly, so the two-index family is
     generated by the one-index field Phi.  Proposition 3 of
     ``docs/analysis/phase_alignment_microdynamics.md`` holds for arbitrary
     index pairs, not only for partners.

  B  The obstruction.  Lemma 1's darkness condition fixes only the
     *difference* of a pair's phases, leaving a free per-pair carrier.
     Averaging cos mu over all pairs is carrier-sensitive; averaging over
     partnered pairs is not.  With free carriers the all-pairs average is
     suppressed by 1/B and the reformulation fails.

  C  The carrier-lock postulate (S).  Impose a common transported phase per
     (cell, row) -- the literal reading of "phase-space *crystal* lattice"
     -- and the all-pairs average equals the indexed average identically.

  D  Factorisation.  Under (S) the double sum over admissible pairs
     collapses exactly onto a per-cell, per-row order parameter
         Z_n(x) = sum_j exp(i Phi_j(x,t)),
     turning the O(N_exc * B) vertex loop of §4 into O(N_exc + N_sea).

  E  Calibration.  The quadrature built from Z alone reproduces
     Gamma_q(x) = -(V_q/hbar) sin(K_q x + phi_q) with the corrected sign,
     the carrier cancelling identically.

  F  The deciding experiment.  Under per-particle noise the two forms agree
     in the mean and differ in variance by sqrt(N).  Under pair-correlated
     noise -- a sea of individually aligned but mutually randomised pairs --
     they differ in the mean, the indexed form reporting full response where
     the relational form reports none.

  H  Cells and rows.  The two labels in postulate (S) are not the same
     kind of thing: a momentum row is an exact lattice site, a spatial
     cell is a sweepable quadrature bin.  Part H verifies that same-row
     particles contribute identical transported phase regardless of
     their positions within the cell, and that the one place cell width
     does enter -- the pump, which samples V at each particle's own
     position -- produces a bounded rather than secular loss of carrier
     lock under free streaming.

  G  Sea consumption.  Corollaries 4.2/4.3 leave a struck pair with
     Delta p = 0 and hence permanently inert, so an indexed sea is a
     consumable resource with no replenishment in §6.  Part G sizes the
     deficit for the cosine-well demo.

Conventions follow the rest of the project: ring [0, L), half-grid
dp = pi hbar / L, mode quantum 2q dp = hbar K_q, stencil rows n +- q.
"""

from __future__ import annotations

import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from wpmwlib.wpmw_utils import output_path, docs_path  # noqa: E402


HBAR = 1.0
MASS = 1.0
L = 8.0
DP = np.pi * HBAR / L
Q_MODE = 1
K_MODE = 2.0 * np.pi * Q_MODE / L
V_P = 1.5
PHI_Q = 0.7
SEED = 20260728


def wrap(a):
    """Wrap to (-pi, pi]."""
    return (a + np.pi) % (2.0 * np.pi) - np.pi


def transported_phase(x_ref, p, theta, x, t):
    """Phi(x,t) = theta + [p (x - x_ref) - E t] / hbar,  E = p^2 / 2m."""
    return theta + (p * (x - x_ref) - p ** 2 / (2.0 * MASS) * t) / HBAR


def banner(s):
    print()
    print("=" * 74)
    print(s)
    print("=" * 74)


# --------------------------------------------------------------------- #
# Part A -- coboundary structure                                        #
# --------------------------------------------------------------------- #
def part_A(rng):
    banner("Part A -- mu is a coboundary of Phi; no partnership is stored")

    N = 40
    p = rng.integers(-6, 7, size=N) * 2 * DP           # even sites, §1
    x_ref = rng.uniform(0.0, L, size=N)
    theta = rng.uniform(0.0, 2.0 * np.pi, size=N)

    xs, ts = 2.3, 1.7
    Phi = transported_phase(x_ref, p, theta, xs, ts)
    mu = wrap(Phi[:, None] - Phi[None, :])

    anti = np.max(np.abs(wrap(mu + mu.T)))
    tri = np.max(np.abs(wrap(mu[:, :, None] + mu[None, :, :] - mu[:, None, :])))

    alpha = 0.9137
    Phi_g = transported_phase(x_ref, p, theta + alpha, xs, ts)
    gauge = np.max(np.abs(wrap(mu - wrap(Phi_g[:, None] - Phi_g[None, :]))))

    # Re-referencing: advance each leg to epoch t1 along its own worldline,
    # winding theta at the Lagrangian rate and shifting the time origin.
    t1 = 0.63
    x2 = x_ref + p / MASS * t1
    th2 = theta + (p ** 2 / (2.0 * MASS)) * t1 / HBAR
    Phi_r = transported_phase(x2, p, th2, xs, ts - t1)
    reref = np.max(np.abs(wrap(mu - wrap(Phi_r[:, None] - Phi_r[None, :]))))

    print(f"  ensemble size                              N = {N}")
    print(f"  antisymmetry    max|mu_ij + mu_ji|           = {anti:.3e}")
    print(f"  cocycle         max|mu_ij + mu_jk - mu_ik|   = {tri:.3e}")
    print(f"  global gauge    max|delta mu|                = {gauge:.3e}")
    print(f"  re-referencing  max|delta mu|                = {reref:.3e}")

    # Proposition 3 for arbitrary index pairs, by central differences.
    eps = 1e-5
    dpm = (p[:, None] - p[None, :]) / HBAR
    vbar = (p[:, None] + p[None, :]) / (2.0 * MASS)

    def mu_at(x, t):
        f = transported_phase(x_ref, p, theta, x, t)
        return f[:, None] - f[None, :]

    dx_num = (mu_at(xs + eps, ts) - mu_at(xs - eps, ts)) / (2 * eps)
    err_x = np.max(np.abs(dx_num - dpm))

    v = 0.37
    dt_num = (mu_at(xs + v * eps, ts + eps)
              - mu_at(xs - v * eps, ts - eps)) / (2 * eps)
    err_t = np.max(np.abs(dt_num - dpm * (v - vbar)))

    print(f"  Prop 3, all pairs   max|d_x mu - Dp/hbar|    = {err_x:.3e}")
    print(f"  Prop 3, all pairs   max|dmu/dt - (Dp/h)(v-v)| = {err_t:.3e}")
    print("  -> the two-index family is generated by the one-index field Phi.")
    print("     A stored partner index carries no state; it can only select.")
    return dict(anti=anti, tri=tri, gauge=gauge, reref=reref)


# --------------------------------------------------------------------- #
# Part B -- the carrier obstruction                                     #
# --------------------------------------------------------------------- #
def part_B(rng):
    banner("Part B -- the obstruction: a free per-pair carrier kills all-pairs")

    mu0 = 0.7
    print(f"  true misalignment mu = {mu0}, cos mu = {np.cos(mu0):+.6f}")
    print()
    print(f"  {'B':>6s} {'partnered <cos mu>':>22s} "
          f"{'all-pairs <cos mu>':>22s}")
    rows = []
    for B in (32, 128, 512, 2048, 8192):
        chi = rng.uniform(0.0, 2.0 * np.pi, size=B)     # free carrier per pair
        Phi_lo, Phi_hi = chi, chi + mu0
        part = np.mean(np.cos(wrap(Phi_hi - Phi_lo)))
        allp = np.real(np.exp(1j * Phi_hi).sum()
                       * np.conj(np.exp(1j * Phi_lo).sum())) / B ** 2
        rows.append((B, part, allp))
        print(f"  {B:6d} {part:22.9f} {allp:22.9f}")
    print()
    print("  Lemma 1 fixes only theta_a - theta_b within a pair; the common")
    print("  value is unconstrained.  Under that reading mu_{ij} across")
    print("  different pairs is not gauge invariant, and Bill's definition")
    print("  averages to zero as 1/B.  The reformulation needs one more")
    print("  ingredient, supplied in Part C.")
    return rows


# --------------------------------------------------------------------- #
# Part C -- the carrier-lock postulate                                  #
# --------------------------------------------------------------------- #
def part_C(rng):
    banner("Part C -- postulate (S), carrier lock: all-pairs == partnered")

    B = 2000
    x_cell, t = 3.1, 0.0
    s = +1
    mu_place = wrap(s * (K_MODE * x_cell + PHI_Q) + np.pi / 2.0)

    chi = rng.uniform(0.0, 2.0 * np.pi)                 # ONE carrier per site
    Phi_lo = np.full(B, chi)
    Phi_hi = np.full(B, chi + mu_place)

    part = np.mean(np.cos(wrap(Phi_hi - Phi_lo)))
    Zh = np.exp(1j * Phi_hi).sum()
    Zl = np.exp(1j * Phi_lo).sum()
    allp = np.real(Zh * np.conj(Zl)) / B ** 2

    print(f"  B = {B} sea particles per row at the site, t = {t}")
    print(f"  mu(place)                              = {mu_place:+.15f}")
    print(f"  partnered <cos mu>                     = {part:+.15f}")
    print(f"  all-pairs Re(Zhat_hi conj(Zhat_lo))    = {allp:+.15f}")
    print(f"  cos(mu_place)                          = "
          f"{np.cos(mu_place):+.15f}")
    print(f"  |all-pairs - partnered|                = "
          f"{abs(allp - part):.3e}")
    print(f"  |Zhat_hi| = {abs(Zh) / B:.15f}, |Zhat_lo| = {abs(Zl) / B:.15f}")
    print("  -> under (S) the indexed rule is the |Zhat| = 1 limit of the")
    print("     relational rule, and the site carrier chi cancels exactly.")
    return dict(mu_place=mu_place, part=part, allp=allp)


# --------------------------------------------------------------------- #
# Part D -- factorisation                                               #
# --------------------------------------------------------------------- #
def part_D(rng):
    banner("Part D -- exact factorisation of the relational vertex sum")

    w0, kappa = 0.25, 0.10
    print(f"  w0 = {w0}, kappa = {kappa}   (clamp: kappa <= min(w0, 1-w0))")
    print()
    print(f"  {'N_hi':>7s} {'N_lo':>7s} {'direct O(N^2)':>18s} "
          f"{'factorised O(N)':>18s} {'rel.err':>10s} {'speedup':>9s}")
    rows = []
    for n in (8, 32, 128, 512, 2048, 8192):
        Phi_hi = rng.uniform(0.0, 2.0 * np.pi, size=n)
        Phi_lo = rng.uniform(0.0, 2.0 * np.pi, size=n)

        t0 = time.perf_counter()
        direct = np.sum(w0 + kappa * np.cos(Phi_hi[:, None] - Phi_lo[None, :]))
        t_d = time.perf_counter() - t0

        t0 = time.perf_counter()
        Zh = np.exp(1j * Phi_hi).sum()
        Zl = np.exp(1j * Phi_lo).sum()
        fact = w0 * n * n + kappa * np.real(Zh * np.conj(Zl))
        t_f = time.perf_counter() - t0

        rel = abs(direct - fact) / abs(direct)
        rows.append((n, rel, t_d / t_f))
        print(f"  {n:7d} {n:7d} {direct:18.10e} {fact:18.10e} "
              f"{rel:10.2e} {t_d / t_f:8.1f}x")

    print()
    print("  Identity (exact, not an approximation):")
    print("    sum_{a,b} [w0 + kappa cos(Phi_a - Phi_b)]")
    print("      = w0 N_hi N_lo + kappa Re( Z_hi conj(Z_lo) ).")
    print("  §4's O(N_exc * B) encounter loop becomes O(N_exc + N_sea), and")
    print("  the sea-subsampling workaround of §4 becomes unnecessary.")
    return rows


# --------------------------------------------------------------------- #
# Part E -- Gamma_q(x) from Z alone                                     #
# --------------------------------------------------------------------- #
def part_E(rng, M=64, B=400, tau_p=0.02):
    banner("Part E -- Gamma_q(x) recovered from Z alone (no partner indices)")

    x_cells = (np.arange(M) + 0.5) * (L / M)
    mu1 = V_P * tau_p / HBAR                            # pumped contrast C
    net = np.zeros(M)

    for m, xc in enumerate(x_cells):
        rate = 0.0
        for s in (+1, -1):
            chi = rng.uniform(0.0, 2.0 * np.pi)         # site carrier, (S)
            mu_s = s * (K_MODE * xc + PHI_Q) + np.pi / 2.0
            Zh = np.exp(1j * (chi + mu_s)) * B
            Zl = np.exp(1j * chi) * B
            bias = np.real(Zh * np.conj(Zl)) / B ** 2
            rate += 0.5 * mu1 * s * bias                # s = hop direction
        net[m] = rate / tau_p                            # per unit time

    gamma_exact = -(V_P / HBAR) * np.sin(K_MODE * x_cells + PHI_Q)
    rel = np.max(np.abs(net - gamma_exact)) / np.max(np.abs(gamma_exact))

    print(f"  M = {M} cells, B = {B} per row per family, tau_p = {tau_p}")
    print(f"  contrast mu1 = V_p tau_p / hbar = {mu1:.4f}, phi_q = {PHI_Q}")
    print(f"  max|recovered - Gamma_q| / max|Gamma_q| = {rel:.3e}")
    print(f"  at x = L/4 : recovered = {net[M // 4]:+.9f}, "
          f"exact = {gamma_exact[M // 4]:+.9f}")
    print("  -> corrected-sign Gamma_q(x) = -(V_q/hbar) sin(K_q x + phi_q),")
    print("     with the arbitrary site carrier cancelling identically.")
    return x_cells, net, gamma_exact, rel


# --------------------------------------------------------------------- #
# Part F -- the deciding experiment                                     #
# --------------------------------------------------------------------- #
def part_F(rng, n_trials=400):
    banner("Part F -- the deciding experiment: two decoherence models")

    mu0 = 0.7
    Ns = np.array([16, 64, 256, 1024, 4096])

    print("  Model I -- independent per-particle phase noise (uniform):")
    print(f"  {'N':>6s} {'partnered rms':>16s} {'relational rms':>17s} "
          f"{'ratio':>8s}")
    rms_p, rms_r = [], []
    for N in Ns:
        vp, vr = [], []
        for _ in range(n_trials):
            da = rng.uniform(0.0, 2.0 * np.pi, size=N)
            db = rng.uniform(0.0, 2.0 * np.pi, size=N)
            vp.append(np.mean(np.cos(mu0 + da - db)))
            Zh = np.exp(1j * (mu0 + da)).sum()
            Zl = np.exp(1j * db).sum()
            vr.append(np.real(Zh * np.conj(Zl)) / N ** 2)
        rp = float(np.sqrt(np.mean(np.square(vp))))
        rr = float(np.sqrt(np.mean(np.square(vr))))
        rms_p.append(rp)
        rms_r.append(rr)
        print(f"  {N:6d} {rp:16.4e} {rr:17.4e} {rp / rr:7.1f}x")

    ep = float(np.polyfit(np.log(Ns), np.log(rms_p), 1)[0])
    er = float(np.polyfit(np.log(Ns), np.log(rms_r), 1)[0])
    print(f"  fitted exponents:  partnered N^({ep:+.3f}),  "
          f"relational N^({er:+.3f})")
    print("  -> identical mean (zero); relational form is sqrt(N) quieter.")
    print()
    print("  Model II -- pair-correlated noise: each pair keeps its own mu,")
    print("              pairs mutually randomised (Lemma 5 violated):")
    N = 4096
    delta = rng.uniform(0.0, 2.0 * np.pi, size=N)
    Phi_lo, Phi_hi = delta, delta + mu0
    part = float(np.mean(np.cos(wrap(Phi_hi - Phi_lo))))
    Zh = np.exp(1j * Phi_hi).sum()
    Zl = np.exp(1j * Phi_lo).sum()
    rel = float(np.real(Zh * np.conj(Zl)) / N ** 2)
    print(f"  N = {N},  mu = {mu0}")
    print(f"  partnered  <cos mu>                  = {part:+.6f}  "
          f"(= cos mu, full response)")
    print(f"  relational Re(Zhat_hi conj(Zhat_lo)) = {rel:+.6f}  "
          f"(suppressed ~ 1/N)")
    print("  -> the two forms disagree in the MEAN, not just in variance.")
    print("     The partnered estimator reports a coherent grating where")
    print("     there is none; it cannot detect failure of Lemma 5, which")
    print("     is the assumption it silently makes.")
    return Ns, np.array(rms_p), np.array(rms_r), ep, er, part, rel


# --------------------------------------------------------------------- #
# Part G -- sea consumption                                             #
# --------------------------------------------------------------------- #
def part_G():
    banner("Part G -- an indexed sea is consumable; a relational sea is not")

    omega = np.sqrt(V_P * (2.0 * np.pi / L) ** 2 / MASS)
    T_period = 2.0 * np.pi / omega
    T_final = 4.0 * T_period
    N_exc, M, B = 5_000_000, 128, 2_000
    gamma_max = V_P / HBAR
    fires = gamma_max * T_final * N_exc / M

    print(f"  cosine-well demo: V_p = {V_P}, L = {L}, "
          f"N_exc = {N_exc:,}, M = {M}")
    print(f"  harmonic period T = {T_period:.3f}, T_final = {T_final:.3f}")
    print(f"  max|Gamma_q| = V_p/hbar = {gamma_max}")
    print(f"  NET firings required per cell over the run   ~ {fires:.3e}")
    print(f"  distinct pairs available per cell (B = {B})   = {B:.3e}")
    print(f"  shortfall factor                             ~ {fires / B:.2e}")
    print("  (gross traffic at rate w0 makes this a lower bound)")
    print()
    print("  Corollary 4.2 leaves a struck pair at Delta p = 0; Corollary 4.3")
    print("  then gives it transfer size |Delta p| = 0, so it can never")
    print("  mediate again.  §6's pump writes phases only (Lemma 3), so")
    print("  nothing replenishes the split population, and §9's reference")
    print("  loop populates pairs once at initialisation.  Under the")
    print("  relational definition, admissibility is re-derived from row")
    print("  occupancy each step, so a struck particle rejoins the")
    print("  admissible set immediately and the resource never depletes.")
    return fires, B


# --------------------------------------------------------------------- #
# Figure                                                                #
# --------------------------------------------------------------------- #
def part_H(rng, M=128, B=400):
    banner("Part H -- cells are swept, rows are exact")

    dx = L / M
    print(f"  L = {L}, M = {M}, dx = {dx:.6f}, dp = pi*hbar/L = {DP:.6f}")
    print(f"  particle row spacing 2*dp   = {2 * DP:.6f}")
    print(f"  mode-1 quantum hbar*K_1     = {HBAR * K_MODE:.6f}   (identical)")
    print(f"  phase-space cell dx*dp      = {dx * DP:.6f}")
    print(f"  Planck cell h               = {2 * np.pi * HBAR:.6f}"
          f"   ratio = {dx * DP / (2 * np.pi * HBAR):.5f}")

    # (i) same row, different x within the cell: phases coincide exactly.
    xc = 3.0 + dx / 2.0
    r = 4                                              # even row
    p_r = r * DP
    xj = xc + rng.uniform(-dx / 2.0, dx / 2.0, 5)
    theta = p_r * xj / HBAR                            # common gauge invariant
    Phi = transported_phase(xj, p_r, theta, xc, 0.0)
    print(f"  five particles on row {r}, spread across one cell:")
    print(f"    max spread of Phi(x_cell) = {np.ptp(Phi):.3e}")
    print(f"    |Zhat|                    = "
          f"{abs(np.exp(1j * Phi).mean()):.15f}")
    print("  -> intra-cell separation contributes nothing: Phi is a field,")
    print("     and same-row legs share p, hence share E.")

    # (ii) the one place dx enters: the pump samples V at each own x.
    tau_p, T = 0.02, 26.13
    nsteps = int(T / tau_p)
    xj = xc + rng.uniform(-dx / 2.0, dx / 2.0, B)
    th = np.zeros(B)
    ts, mods = [], []
    for k in range(nsteps):
        th -= V_P * np.cos(K_MODE * xj) * tau_p / HBAR
        xj = (xj + p_r / MASS * tau_p) % L
        if k % 10 == 0:
            ts.append(k * tau_p)
            mods.append(abs(np.exp(1j * (th - th.mean())).mean()))
    ts, mods = np.array(ts), np.array(mods)
    half = len(mods) // 2
    print(f"  predicted per-pump spread ~ mu1*K*dx = "
          f"{V_P * tau_p / HBAR * K_MODE * dx:.3e} rad")
    print(f"  |Zhat| over {nsteps} pumps: min = {mods.min():.6f}, "
          f"max = {mods.max():.6f}")
    print(f"  first-half mean {mods[:half].mean():.6f}, "
          f"second-half mean {mods[half:].mean():.6f}")
    print("  -> bounded and oscillatory, not secular: same-row legs share a")
    print("     velocity, so each samples the same V over a ring transit.")
    return ts, mods, dx


def draw_lattice(ax, q=1):
    """Schematic of the (x, p) lattice: exact rows, sweepable cells."""
    ncell, nrow = 10, 7
    for k in range(ncell + 1):
        ax.axvline(k, color="0.75", lw=0.6, ls=":", zorder=0)
    ax.axvspan(3, 4, color="C1", alpha=0.12, zorder=0)

    rows = np.arange(nrow) - nrow // 2          # offsets from midpoint n
    for j in rows:
        even = (j - q) % 2 == 0                 # particle rows: n +- odd q
        if j in (-q, q):
            ax.axhline(j, color="C1", lw=2.0, zorder=1)
        elif even:
            ax.axhline(j, color="0.45", lw=1.1, zorder=1)
        else:
            ax.axhline(j, color="0.72", lw=0.8, ls=(0, (5, 4)), zorder=1)

    xs = np.array([3.15, 3.32, 3.68, 3.85])
    for y in (-q, q):
        ax.plot(xs, np.full_like(xs, y), "o", ms=6, color="C1",
                mec="0.25", mew=0.6, zorder=3)
    ax.plot([3.5], [-q], "o", ms=11, color="C0", mec="0.15", mew=0.9,
            zorder=4)
    ax.annotate("", xy=(3.5, q - 0.12), xytext=(3.5, -q + 0.12),
                arrowprops=dict(arrowstyle="-|>", color="C0", lw=1.8))

    ax.text(10.25, q, "$r + 2q$   out row", va="center", fontsize=9)
    ax.text(10.25, 0, "$n = r + q$   beat, empty", va="center", fontsize=9)
    ax.text(10.25, -q, "$r$   in row", va="center", fontsize=9)
    ax.annotate("", xy=(4, -3.55), xytext=(3, -3.55),
                arrowprops=dict(arrowstyle="<->", color="0.35", lw=1.0))
    ax.text(3.5, -3.95, r"$\Delta x = L/M$  (swept)", ha="center",
            fontsize=9, color="0.25")
    ax.set_xlim(-0.2, 10.2)
    ax.set_ylim(-4.4, 3.6)
    ax.set_xlabel("$x$   (cells: quadrature bins, refinable)")
    ax.set_ylabel(r"$p = n\,dp$,   $dp = \pi\hbar/L$   (exact)")
    ax.set_xticks([])
    ax.set_yticks([])
    for sp in ("top", "right", "bottom", "left"):
        ax.spines[sp].set_visible(False)
    ax.set_title("(a) rows are exact lattice sites; cells are swept",
                 fontsize=10)


def make_figure(dB, dE, dF):
    x_cells, net, gamma_exact, rel = dE
    Ns, rms_p, rms_r, ep, er, _, _ = dF

    fig, axes = plt.subplots(1, 3, figsize=(15.0, 4.2))

    ax = axes[0]
    Bs = np.array([r[0] for r in dB], dtype=float)
    partv = np.array([r[1] for r in dB])
    allv = np.abs([r[2] for r in dB])
    ax.semilogx(Bs, partv, "s-", color="C0", label="partnered (indexed)")
    ax.semilogx(Bs, allv, "o-", color="C3", label="all pairs, free carrier")
    ax.axhline(np.cos(0.7), ls="--", color="0.5", lw=1,
               label=r"$\cos\mu$")
    ax.set_xlabel("pairs per site, $B$")
    ax.set_ylabel(r"$\langle\cos\mu\rangle$")
    ax.set_title("(a) the obstruction: a free per-pair\n"
                 "carrier destroys the all-pairs average", fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3, which="both")

    ax = axes[1]
    ax.plot(x_cells, gamma_exact, "-", lw=2.5, color="0.6",
            label=r"$-(V_q/\hbar)\sin(K_q x + \phi_q)$")
    ax.plot(x_cells, net, "o", ms=4, color="C3",
            label=r"from $\mathrm{Re}(\hat Z_{n+q}\overline{\hat Z_{n-q}})$")
    ax.set_xlabel("$x$")
    ax.set_ylabel(r"$\Gamma_q(x)$")
    ax.set_title("(b) under carrier lock (S): stencil rate\n"
                 f"from $Z$ alone, rel. residual $= {rel:.1e}$", fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    ax = axes[2]
    ax.loglog(Ns, rms_p, "s-", color="C0",
              label=f"partnered $\\sim N^{{{ep:+.2f}}}$")
    ax.loglog(Ns, rms_r, "o-", color="C3",
              label=f"relational $\\sim N^{{{er:+.2f}}}$")
    ax.set_xlabel("sea particles per row per site, $N$")
    ax.set_ylabel("rms residual bias")
    ax.set_title("(c) decoherent limit (Model I):\n"
                 r"relational form is $\sqrt{N}$ quieter", fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3, which="both")

    fig.suptitle("Relational (all-pairs) misalignment and the carrier-lock "
                 "condition", fontsize=12)
    fig.tight_layout()
    fig.savefig(output_path("relational_pairing.png"), dpi=150,
                bbox_inches="tight")
    d = docs_path("figures/relational_pairing.png")
    if d:
        fig.savefig(d, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print()
    print(f"  figure -> {output_path('relational_pairing.png')}")


def make_lattice_figure(dH):
    ts, mods, dx = dH
    fig, axes = plt.subplots(1, 2, figsize=(12.5, 4.4),
                             gridspec_kw=dict(width_ratios=[1.35, 1.0]))
    draw_lattice(axes[0])

    ax = axes[1]
    ax.plot(ts, mods, "-", lw=1.0, color="C3")
    ax.axhline(1.0, color="0.6", lw=1.0, ls="--")
    ax.set_xlabel("$t$")
    ax.set_ylabel(r"$|\hat{Z}_r(x)|$")
    ax.set_title("(b) the one effect of cell width: intra-cell pump\n"
                 "spread is bounded, not secular", fontsize=10)
    ax.grid(alpha=0.3)

    fig.suptitle("Cells and rows in postulate (S)", fontsize=12)
    fig.tight_layout()
    fig.savefig(output_path("lattice_cells_and_rows.png"), dpi=150,
                bbox_inches="tight")
    d = docs_path("figures/lattice_cells_and_rows.png")
    if d:
        fig.savefig(d, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"  figure -> {output_path('lattice_cells_and_rows.png')}")


def main():
    rng = np.random.default_rng(SEED)
    print("Relational (all-pairs) misalignment -- verification")
    print(f"  hbar = {HBAR}, m = {MASS}, L = {L}, dp = {DP:.6f}, "
          f"q = {Q_MODE}, K = {K_MODE:.6f}, phi_q = {PHI_Q}")

    part_A(rng)
    dB = part_B(rng)
    part_C(rng)
    part_D(rng)
    dE = part_E(rng)
    dF = part_F(rng)
    part_G()
    dH = part_H(rng)
    make_figure(dB, dE, dF)
    make_lattice_figure(dH)
    print()
    print("done.")


if __name__ == "__main__":
    main()
